### ISSUE TITLE
Allow options as tags

### ISSUE THREAD

**Issue by clason** [vigoux/tree-sitter-vimdoc#3]
Currently, the parser only allows a simple `word` as `tag`, as in `*foo*`; `option` like `*'sw'*` and `argument` like `{subject}` (possibly the only instance) are a parsing error.

**Comment by vigoux** [comment]
I think we need a deeper redesign of the parser, to avoid the reliance on `scanner.c` and to allow more flexilibity like this.
I am going to look into it !
