### ISSUE TITLE
Some whole paragraphs colored

### ISSUE THREAD

**Issue by d12bb** [vigoux/tree-sitter-vimdoc#4]
When having TS enabled with highlight, often there are whole paragraphs highlighted, for me (gruvbox-baby) in yellow. Example from `usr_03.txt` below:

With TS:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/16717303/167247137-4cd2e440-ad4a-4de0-bfd8-3ae55a0a0105.png">
Without TS:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/16717303/167247122-1113252a-d3b2-49dc-9e26-cb747b864c96.png">

**Comment by vigoux** [comment]
Hi and thanks for reporting.
I'll try to see what the problem is here and fix it.
